ARG APP_IMAGE=ghcr.io/pethalyse/kcdle-app:latest
FROM ${APP_IMAGE} as app_public

FROM nginx:1.27
COPY docker/nginx/default.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=app_public /var/www/html/public /var/www/html/public
