<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Auth\Events\Verified;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class EmailVerificationController extends Controller
{
    /**
     * Verify the user's email address.
     *
     * This controller is meant to be called via a signed URL generated by the
     * verification notification. If the signature is valid and the hash
     * matches the user's email, the email is marked as verified.
     *
     * The user is then redirected to the frontend with a status flag.
     *
     * @param Request $request Incoming HTTP request.
     * @param int $id User identifier.
     * @param string $hash Email hash for verification.
     *
     * @return RedirectResponse Redirect to the frontend.
     */
    public function __invoke(Request $request, int $id, string $hash): RedirectResponse
    {
        /** @var User|null $user */
        $user = User::query()->find($id);

        $frontend = rtrim((string) config('app.frontend_url'), '/');

        if (! $user) {
            return redirect()->to($frontend . '/login?verified=0&reason=user_not_found', Response::HTTP_FOUND);
        }

        if (! hash_equals(sha1($user->getEmailForVerification()), $hash)) {
            return redirect()->to($frontend . '/login?verified=0&reason=invalid_hash', Response::HTTP_FOUND);
        }

        if (! $user->hasVerifiedEmail()) {
            $user->markEmailAsVerified();
            event(new Verified($user));
        }

        $user->tokens()->delete();

        $token = $user->createToken('kcdle-app')->plainTextToken;

        return redirect()->to($frontend . '/login?verified=1&token=' . urlencode($token), Response::HTTP_FOUND);
    }
}
